# Generated by Django 5.1 on 2024-10-17 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.GenericIPAddressField()),
                ('start_port', models.IntegerField()),
                ('end_port', models.IntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.IntegerField()),
                ('status', models.CharField(max_length=200)),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='port_scanner_app.request')),
            ],
        ),
    ]
